let buildingListMk1 = [
	{id: 0,name: "caserne1", price: 2000, income: -50, ecologie: -5, economie: -5, bienEtre: 5, pop: 0, description: "La caserne de pompier est un bâtiment peu coûteux en entretien et qui consomme peu, mais qui donne un sentiment de sécurité aux citoyens de la ville, car ils se sentent protégés en cas de problèmes comme les incendies.",x:0,y:-10, popMin: 0},
	{id: 1,name : "centrale1", price: 5750, income: -150, ecologie: -12, economie: -7, bienEtre: 9, pop: 0, description: "La centrale électrique est un bâtiment très polluant et très coûteux en entretien, mais qui permet au habitants d'avoir une ressource indispensable pour une ville moderne: l'électricité.",x:0, y:-30, popMin: 0},
	{id: 2,name : "commissariat1", price: 2000, income: -50, ecologie: -3, economie: -2, bienEtre: 5, pop: 0, description: "Le commissariat est un bâtiment peu coûteux en entretien qui donne un sentiment de sécurité à la population.",x:0, y: -10, popMin: 0},
	{id: 3,name : "école1", price: 2500, income: -50, ecologie: -3, economie: -5, bienEtre: 5, pop: 0, description: "L'école est un bâtiment peu coûteux en entretien, qui pollue peu et est indispensable pour le bien être de la population.",x:30, y:-10, popMin: 0},
	{id: 4,name	: "hopital1", price : 5000, income: -50, ecologie: -5, economie: -5, bienEtre: 5, pop: 0, description: "L'hôpital est un bâtiment coûteux en entretien et polluant mais qui donne un confort de vie à la population en cas de maladie ou d'accident.",x:50, y: -50, popMin: 0},
	{id: 5,name : "poste1", price: 1500, income: -50, ecologie: -1, economie: -2, bienEtre: 5, pop: 0, description: "La poste est un bâtiment peu coûteux en entretien et peu polluant qui augmente le bien-être des habitants(quand les guichets sont ouverts).",x:0, y: -10, popMin: 0},
	{id: 6,name	: "centrale_hydraulique1", price: 9500, income : -350, ecologie : 10, economie : -15, bienEtre: 0, pop: 0, description: "La centrale hydraulique est un bâtiment tres coûteux en entretien mais qui permet produire de l'électricité de manière renouvelable, elle améliore donc beaucoup la statistique d'écologie.",x: -70, y:-40,sizeX: 1,sizeY: 2, popMin: 0},
	{id: 7,name : "panneau_solaire", price: 6500, income: -150, ecologie: 10, economie: -4, bienEtre: 0, pop: 0, description: "Les panneaux solaires sont assez coûteux en entretien mais permettent de produire de l'électricité de manière renouvelable.",x: 0, y:-100,sizeX: 2,sizeY:2, popMin: 0},
	{id: 8, name: "parc1", price: 1000, income: -75, ecologie: 10, economie: -5, bienEtre: 10, pop: 0, description: "Un parc apporte du bien être et du divertissement à la population, et permet à la ville de respiret augmentant donc la statistique d'écologie.", x: 0,y:-10, popMin: 0},
	{id: 9, name: "usine_recyclage1", price: 7500, income: -250, ecologie: 15, economie: -15, bienEtre: -10, pop: 0, description: "Une usine de recyclage est un bâtiment très coûteux en entretien mais qui permet de recycler les déchets de la ville.", x: 0,y:-10, popMin: 0},
	{id: 10, name: "banque1", price: 8500, income: 750, ecologie: -10, economie: 20, bienEtre: 5, pop: 0, description: "La banque est un bâtiment coûteux en entretien, mais essentiel quelque soit la ville car elle permet d'augmenter grandement son économie.",x:30, y: -180, popMin: 0},
	{id: 11, name: "magasin1", price: 1500, income: 300, ecologie: -3, economie: 15, bienEtre: 5, pop: 0, description: "Les magasins permettent à ville de faire vivre son économie. C'est un peu la base du commerce de chaque ville.",x:0, y: -10, popMin: 0},
	{id: 12, name: "usine1", price: 5000, income: 700, ecologie: -30, economie: 14, bienEtre: -10, pop: 0, description: "L'usine est un bâtiment très polluant et bruyant, mais qui contribue énormément à l'économie de la ville et rapporte beaucoup.", x:20, y: -10, popMin: 0},
	{id: 13, name: "mairie1", price: 5000, income: -50, ecologie: 0, economie: 0, bienEtre: 0, pop: 0, description: "La mairie est le bâtiment à partir duquel vous allez pouvoir acheter des avancées technologiques. L'améliorer permet aussi de pouvoir améliorer les autres bâtiments.", x:0,y:-40, popMin: 0},
	{id: 14, name: "maison1", price: 1000, income: 100, ecologie: -5, economie: 5, bienEtre: 2, pop: 100, description: "Les maisons sont essentielles pour avoir des hâbitants dans la ville. Cependant elles demandent un petit coût en entretien et consomment un peu.",x:0,y:-40, popMin: 0},
];

let buildingListMk2 = [
	{id: 0,name: "caserne2", price: 3500, income: -30, ecologie: -3, economie: -2.5, bienEtre: 10, pop: 0, description: "La caserne de pompier est un bâtiment peu coûteux en entretien et qui consomme peu, mais qui donne un sentiment de sécurité aux citoyens de la ville, car ils se sentent protégés en cas de problèmes comme les incendies.La caserne au niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits. Avoir une meilleure caserne des pompiers augmente encore plus le bien-être des habitants.",x:100,y:-100, popMin: 0},
	{id: 1,name : "centrale2", price: 8000, income : -120, ecologie: -8, economie: -5, bienEtre: -5, pop: 0, description: "La centrale électrique est un bâtiment très polluant et très coûteux en entretien, mais qui permet au habitants d'avoir une ressource indispensable pour une ville moderne: l'électricité.La centrale au niveau 2 possède de meilleures techniques pour produire de l'électricité, moins polluantes, ce qui augmente donc les revenus et baisse moins l'écologie.",x:0,y:0,sizeX:1,sizeY:2, popMin: 0},
	{id: 2,name : "commissariat2", price: 3500, income: -30, ecologie: -3, economie: -2.5, bienEtre: 10, pop: 0, description: "Le commissariat est un bâtiment peu coûteux en entretien qui donne un sentiment de sécurité à la population.Le commissariat niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits. Avoir un meilleure commissariat augmente encore plus le bien-être des habitants, se sentant plus en sécurité.",x:0,y:0, popMin :0},
	{id: 3,name : "école2", price: 3500, income: -30, ecologie: -3, economie: -2.5, bienEtre: 10, pop: 0, description: "L'école est un bâtiment peu coûteux en entretien, qui pollue peu et est indispensable pour le bien être de la population.L'école au niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits. Avoir une meilleure école augmente encore plus le bien-être des habitants.",x:0,y:0,sizeX:1,sizeY:2, popMin: 0},
	{id: 4,name	: "hopital2", price : 3500, income: -30, ecologie: -3, economie: -2.5, bienEtre: 10, pop: 0, description: "L'hôpital est un bâtiment coûteux en entretien et polluant mais qui donne un confort de vie à la population en cas de maladie ou d'accident.L'hôpital'au niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits. Avoir un meilleur hôpital augmente encore plus le bien-être des habitants.",x:0,y:0, popMin: 0},
	{id: 5,name : "poste2", price: 3500, income: -30, ecologie: -3, economie: -2.5, bienEtre: 10, pop: 0, description: "La poste est un bâtiment peu coûteux en entretien et peu polluant qui augmente le bien-être des habitants(quand les guichets sont ouverts).La poste  au niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits. Avoir une meilleure poste augmente encore plus le bien-être des habitants.",x:0,y:0,sizeX:2,sizeY:1, popMin: 0},
	{id: 6,name	: "centrale_hydraulique2", price: 12000, income : -250, ecologie : 20, economie : -9, bienEtre: -7, pop: 0, description: "La centrale hydraulique est un bâtiment tres coûteux en entretien mais qui permet produire de l'électricité de manière renouvelable, elle améliore donc beaucoup la statistique d'écologie.La centrale hydraulique au niveau 2 est moins chère en entretien et permet de produire encore plus d'électricité, toujours de manière renouvelable.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 7,name : "panneau_solaire2", price: 9000, income: -100, ecologie: 15, economie: -2, bienEtre: 0, pop: 0, description: "Les panneaux solaires sont assez coûteux en entretien mais permettent de produire de l'électricité de manière renouvelable.Les panneaux solaires niveaux 2 sont moins coûteux en entretien et permettent de produire plus d'électricité de manière renouvelable.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 8, name: "parc2", price: 2500, income: -80, ecologie: 15, economie: -8, bienEtre: 15, description: "Un parc apporte du bien être et du divertissement à la population, et permet à la ville de respiret augmentant donc la statistique d'écologie.Les parcs au niveau 2 sont moins coûteux en entretien et sont plus modernes, augmentant ainsi le bien être des habitants.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 9, name: "usine_recyclage2", price: 10000, income: -225, ecologie: 20, economie: -10, bienEtre: -5, pop: 0, description: "Une usine de recyclage est un bâtiment très coûteux en entretien mais qui permet de recycler les déchets de la ville.L'usine de recylcage au niveau 2 est moins coûteuse en entretien et permet de recycler plus de déchets par jour.",x:0,y:0,sizeX:1,sizeY:2, popMin: 0},
	{id: 10, name: "banque2", price: 12500, income: 1250, ecologie: -7, economie: 25, bienEtre: 7, pop: 0, description: "La banque est un bâtiment coûteux en entretien, mais essentiel quelque soit la ville car elle permet d'augmenter grandement son économie.La banque au niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits. Avoir une meilleure banque augmente les revenus et l'économie.",x:0,y:0, popMin: 0},
	{id: 11, name: "magasin2", price: 2500, income: 450, ecologie: -5, economie: 18, bienEtre: 8, pop: 0, description: "Les magasins permettent à ville de faire vivre son économie. C'est un peu la base du commerce de chaque ville.Les magasins au niveau 2 possèdent une meilleure isolation, augmente les revenus et l'économie.",x:0,y:0,sizeX:1,sizeY:2, popMin: 0},
	{id: 12, name: "usine2", price: 7500, income: 1000, ecologie: -20, economie: 19, bienEtre: -7, pop: 0, description: "L'usine est un bâtiment très polluant et bruyant, mais qui contribue énormément à l'économie de la ville et rapporte beaucoup.Les usines au niveau 2 polluent moins et produisent plus, augmentant ainsi l'économie et les revenus.",x:0,y:0,sizeX:1,sizeY:2, popMin: 0},
	{id: 13, name: "mairie2", price: 15000, income: 0, ecologie: 0, economie: 0, bienEtre: 0, pop: 0, description: "La mairie est le bâtiment à partir duquel vous allez pouvoir acheter des avancées technologiques.La mairie au niveau 2 permet de débloquer les améliorations des autres bâtiments et des technologies de rang 2.",x:-100,y:-100,sizeX:1,sizeY:2, popMin: 0},
	{id: 14, name: "maison2", price: 2500, income: 200, ecologie: -3, economie: 8, bienEtre: 5, pop: 300, description: "Les maisons sont essentielles pour avoir des hâbitants dans la ville. Cependant elles demandent un petit coût en entretien et consomment un peu.Les maisons de niveau 2 ont une meilleure isolation et un coût d'entretien plus faible. Elles permettent aussi d'acceuillir plus de personnes.",x:0,y:0,sizeX:1,sizeY:2, popMin: 0}
];

let buildingListMk3 = [
	{id: 0,name: "caserne3", price: 5000, income: -10, ecologie: 5, economie: -1, bienEtre: 20, pop: 0, description: "La caserne de pompier est un bâtiment peu coûteux en entretien et qui consomme peu, mais qui donne un sentiment de sécurité aux citoyens de la ville, car ils se sentent protégés en cas de problèmes comme les incendies.La caserne au niveau 3 possède des camions de pompiers moins polluants, fonctionnant à l'énergie verte. Avoir une meilleure caserne des pompiers augmente plus le bien-être des habitants, se sentant en sécurité.",x:0,y:-150,sizeX:2,sizeY:1, popMin: 0},
	{id: 1,name : "centrale3", price: 11000, income: -80, ecologie: -2, economie: -2, bienEtre: -1, pop: 0, description: "La centrale électrique est un bâtiment très polluant et très coûteux en entretien, mais qui permet au habitants d'avoir une ressource indispensable pour une ville moderne: l'électricité.La centrale au niveau 3 utilise une technologie révolutionnaire et bien moins polluante: la fusion nucléaire ce qui augmente donc beaucoup les revenus et baisse bien moins l'écologie.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 2,name : "commissariat3", price: 5000, income: -15, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "Le commissariat est un bâtiment peu coûteux en entretien qui donne un sentiment de sécurité à la population.Au commissariat niveau 3, les policiers ont des hélicoptères électriques, moins polluants, permettant d'intervenir plus vite et d'avoir un service plus fiable. Avoir un meilleure commissariat augmente encore plus le bien-être des habitants, se sentant plus en sécurité.",x:0,y:0,sizeX:2,sizeY:1, popMin :0},
	{id: 3,name : "école3", price: 5000, income: -15, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "L'école est un bâtiment peu coûteux en entretien, qui pollue peu et est indispensable pour le bien être de la population.L'école au niveau 3 a des nouvelles techniques d'enseignement. Avoir une meilleure école augmente encore plus le bien-être des habitants.",x:0,y:0,sizeX:1,sizeY:2, popMin: 0},
	{id: 4,name	: "hopital3", price : 5000, income: -15, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "L'hôpital est un bâtiment coûteux en entretien et polluant mais qui donne un confort de vie à la population en cas de maladie ou d'accident.L'hôpital au niveau 3 utilise des techniques modernes de la médecine, plus performantes, économiques et écologiques. Avoir un meilleur hôpital augmente encore plus le bien-être des habitants.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 5,name : "poste3", price: 5000, income: -15, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "La poste est un bâtiment peu coûteux en entretien et peu polluant qui augmente le bien-être des habitants(quand les guichets sont ouverts).La poste  au niveau 3 possède a un réseaux de communication plus performant,elle numérise aussi le courrier pour que les lettres arrivent plus vite.Ce principe est moins polluant et plus économique car il ne fais pas intervenir de transport.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 6,name	: "centrale_hydraulique3", price: 170000, income : -125, ecologie : 40, economie : -4, bienEtre: -3, pop: 0, description: "La centrale hydraulique est un bâtiment tres coûteux en entretien mais qui permet produire de l'électricité de manière renouvelable, elle améliore donc beaucoup la statistique d'écologie.La centrale hydraulique au niveau 3 utilise des techniques plus optimisées, permttant de produire plus d'électricité à moindre coût, toujours de manière renouvelable.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 7,name : "panneau_solaire3", price: 12000, income: -50, ecologie: 30, economie: -1, bienEtre: 0, pop: 0, description: "Les panneaux solaires sont assez coûteux en entretien mais permettent de produire de l'électricité de manière renouvelable.Les panneaux solaires niveaux 3 sont plus optimisés, demandant un coût d'entretien moindre et permettant de produire plus d'électricité de manière renouvelable.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 8, name: "parc3", price: 4000, income: -40, ecologie: 30, economie: -4, bienEtre: 30, pop: 0, description: "Un parc apporte du bien être et du divertissement à la population, et permet à la ville de respiret augmentant donc la statistique d'écologie.Les parcs au niveau 3 ont des espaces verts plus grands, avec plus de poubelles et d'arbres augmentant ainsi le bien être des habitants et l'écologie.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 9, name: "usine_recyclage3", price: 14000, income: -115, ecologie: 40, economie: -5, bienEtre: -3, pop: 0, description: "Une usine de recyclage est un bâtiment très coûteux en entretien mais qui permet de recycler les déchets de la ville.L'usine de recylcage au niveau 3 est plus optimisées permettant de recylcer plus de déchets par jour à moindre coût.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 10, name: "banque3", price: 18000, income: 1700, ecologie: -4, economie: 40, bienEtre: 14, pop: 0, description: "La banque est un bâtiment coûteux en entretien, mais essentiel quelque soit la ville car elle permet d'augmenter grandement son économie.La banque au niveau 3 utilise des intelligences artificielles pour faciliter la demande client,permettant de faire plus de transaction.La sécurité y est aussi fortement augmentée.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 11, name: "magasin3", price: 4000, income: 700, ecologie: -3, economie: 30, bienEtre: 16, pop: 0, description: "Les magasins permettent à ville de faire vivre son économie. C'est un peu la base du commerce de chaque ville.Les magasins au niveau 3 possèdent des sites de vente en ligne, facilitant le commerce et augmentant le bien être des habitants.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 12, name: "usine3", price: 10000, income: 2000, ecologie: -10, economie: 35, bienEtre: -4, pop: 0, description: "L'usine est un bâtiment très polluant et bruyant, mais qui contribue énormément à l'économie de la ville et rapporte beaucoup.Les usines au niveau 3 utilisent des procédés modernes, bien moins polluant et plus rapides, augmentant ainsi l'économie et les revenus et baissant moins la statistique d'écologie.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0},
	{id: 13, name: "mairie3", price: 15000, income: 0, ecologie: 0, economie: 0, bienEtre: 0, pop: 0, description: "La mairie est le bâtiment à partir duquel vous allez pouvoir acheter des avancées technologiques.La mairie au niveau 3 permet de débloquer les améliorations des autres bâtiments et des technologies de rang 3.",x:-200,y:-200,sizeX:2,sizeY:2, popMin: 0},
	{id: 14, name: "maison3", price: 4000, income: 200, ecologie: -2, economie: 10, bienEtre: 10, pop: 500, description: "Les maisons sont essentielles pour avoir des hâbitants dans la ville. Cependant elles demandent un petit coût en entretien et consomment un peu.Les maisons de  niveau 3 utilisent le principe de la domotique, permettant de tout rendre connecté et plus facile d'accès dans la maison, augmentant le bien être. Elles sont plus grandes aussi permettant d'acceuillir beaucoup plus de personnes.",x:0,y:0,sizeX:2,sizeY:2, popMin: 0}
];

let technologieT1 = [
	{id: 0, name: "feuMalvoyant", nom: "Feu Tricolore Malvoyant", price: 1000, ecologie: 0, economie: 0, bienEtre: 5, description: "Installe des Feux Tricolores pour les malvoyants dans la ville, augmentant le bien être et la condition de vie des habitants."},
	{id: 1, name: "signalSonore", nom: "Signal Sonore", price: 1000, ecologie: 0, economie: 0, bienEtre: 5, description: "Installe un Signal Sonore pour Malvoyants au niveau des passages piètons,augmentant le bien être et la condition de vie des habitants."},
	{id: 2, name: "feuSmart", nom: "Feu Intelligent", price: 1000, ecologie: 0, economie: 0, bienEtre: 5, description: "Passe le feu au vert quand un véhicule de secours passe, améliorant les soins et la prise en charge lorsqu'il y a des urgences."},
	{id: 3, name: "peageVehiVert", nom: "Péage gratuit pour véhicule vert", price: 1000, ecologie: 5, economie: 0, bienEtre: 0, description: "Place des péages gratuits pour les véhicules verts, incitant les habitant à utiliser des véhicules vert ce qui augmente donc la statistique d'écologie."},
	{id: 4, name: "e_Admin", nom: "e-administration", price: 1000, ecologie: 0, economie: 3, bienEtre: 3, description: "Créée une application permettant de faire toutes les démarches administratives en ligne, accélerant donc l'économie et améliorant le bien être des habitants."},
	{id: 5, name: "dechetIntell", nom: "Système de gestion des déchets intelligents", price: 1000, ecologie: 5, economie: 0, bienEtre: 0, description: "Permet de trier les déchets de manière plus efficace et plus rapide."},
	{id: 6, name: "passageCamions", nom: "Passage des camions", price: 1000, ecologie: 5, economie: 0, bienEtre: 0, description: "Optimisation du passage des camions réduisant les emissions de CO2."},
	{id: 7, name: "capteurPoub", nom: "Capteur poubelle", price: 1000, ecologie: 5, economie: 0, bienEtre: 0, description: "Capteur pour voir si la poubelle est remplie ou non, accélerant et améliorant le recyclage des déchets."},
	{id: 8, name: "LED", nom: "Lampadaire LED", price: 1000, ecologie: 0, economie: 5, bienEtre: 0, description: "Installation de lampadaires LED qui consomment moins d'énergie et sont donc moins coûteux."}
];

let technologieT2 = [
	{id: 0, name: "voitureElec", nom: "Voiture électrique", price: 2000, ecologie: 0, economie: 10, bienEtre: 0, description: "Utilisation de voitures électriques qui sont moins polluantes, améliorant donc la statistique d'écologie."},
	{id: 1, name: "routeElec", nom: "Route qui recharge la batterie", price: 2000, ecologie: 0, economie: 0, bienEtre: 10, description: "Routes qui rechargent la batterie des voitures électriques, permettant une meilleure autonomie et donc un meilleur confort de vie."},
	{id: 2, name: "parkingSmart", nom: "Parking intelligent", price: 2000, ecologie: 0, economie: 0, bienEtre: 10, description: "Installe des capteurs sur les parkings ce qui donne les places libres grâce à une application."},
	{id: 3, name: "bornes", nom: "Bornes connectées ", price: 2000, ecologie: 0, economie: 0, bienEtre: 10, description: "Installe des bornes connectées dans la ville, permettant de guider les touristes grâce à une carte interactive."},
	{id: 4, name: "compacPoub", nom: "Compacteur poubelle", price: 2000, ecologie: 10, economie: 0, bienEtre: 0, description: "Installe des compacteurs sur les poubelles pour augmenter la capacité de stockage des déchets."},
	{id: 5, name: "IA_Trie", nom: "IA trie", price: 2000, ecologie: 10, economie: 0, bienEtre: 0, description: "Utilise une IA permettant de facilité et d'améliorer davantage le tri des déchets."},
	{id: 6, name: "capteurMouv", nom: "Capteur de mouvement lampadaire", price: 2000, ecologie: 5, economie: 0, bienEtre: 5, description: "Installe des capteurs de mouvement dans la rue, ce qui permet de détecter la présence d'une personne la nuit pour allumer ou non un lampadaire."}
];

let technologieT3 = [
	{id: 0, name: "voitureAuto", nom: "Voiture autonome", price: 3000, ecologie: 0, economie: 0, bienEtre: 15, description: "Permet d'avoir des voitures capable d'aller à un point A à B sans conducteur, améliorant le confort de vie des habitants"},
	{id: 1, name: "IAPolice", nom: "Robot policier", price: 3000, ecologie: 0, economie: 0, bienEtre: 0, description: "IA capable d'intéragir avec des personnes, peut localiser le danger et contacter les secours et intervenir en cas de danger, ce qui donne un sentiement de sécurité aux habitants."},
	{id: 2, name: "tuyauDech", nom: "Réseau de tuyaux souterrains pour déchets", price: 3000, ecologie: 10, economie: 5, bienEtre: 0, description: "Créer un réseau de tuyaux souterrains, ce qui optimise la gestion des déchets."},
	{id: 3, name: "IAClean", nom: "Robot nettoyeur", price: 3000, ecologie: 0, economie: 15, bienEtre: 0, description: "Permet d'avoir des robots pour nettoyer les rues, faisant baisser la pollution."},
	{id: 4, name: "capteurRes", nom: "Capteur sur les réseaux électriques, hydroliques", price: 3000, ecologie: 5, economie: 10, bienEtre: 0, description: "Installe des capteurs permettant de détecter les problèmes de fuites d'eau et autres problèmes, permettant de réduire les pertes d'énergie et d'eau."},
	{id: 5, name: "intelOpe", nom: "Intelligent operation center ", price: 3000, ecologie: 0, economie: 5, bienEtre: 10, description: "Visualisation de toutes les données, big data en temps réel de la ville."}	
];