let buildingListMk1 = [
	{id: 0,name: "caserne1", nom: "Caserne niveau 1", price: 2000, income: -50, ecologie: -5, economie: -5, bienEtre: 5, pop: 0, description: "La caserne de pompier est un bâtiment peu couteux en entretien et qui consomme beaucoup, mais qui donne un sentiment de sécurité aux citoyens de la ville, car ils se sentent protégés en cas de problèmes comme les incendits.",x:0,y:-10, popMin: 200},
	{id: 1,name : "centrale1", nom: "Centrale électrique niveau 1", price: 5750, income: -150, ecologie: -12, economie: -7, bienEtre: 9, pop: 0, description: "La centrale électrique est un bâtiment très polluant et très couteux en entretien, mais qui permet au hâbitants d'avoir une ressource indispensable pour une ville moderne: l'electricité.",x:0, y:-30, popMin: 500},
	{id: 2,name : "commissariat1", nom: "Commissariat niveau 1", price: 2000, income: -50, ecologie: -3, economie: -2, bienEtre: 5, pop: 0, description: "Le commissariat est un bâtiment peu couteux en entretien qui donne un sentiment de sécurité à la population.",x:0, y: -10, popMin: 200},
	{id: 3,name : "école1", nom: "Ecole niveau 1",  price: 2500, income: -50, ecologie: -3, economie: -5, bienEtre: 5, pop: 0, description: "L'école est un bâtiment peu couteux en entretien, qui pollue peu et est indispensable pour le bien être de la population.",x:30, y:-10, popMin: 100},
	{id: 4,name	: "hopital1", nom: "Hôpital niveau 1",  price : 5000, income: -50, ecologie: -5, economie: -5, bienEtre: 5, pop: 0, description: "L'hopital est un bâtiment couteux en entretien et polluant mais qui donne un confort de vie à la population en cas de maladie ou d'accident.",x:50, y: -50, popMin: 300},
	{id: 5,name : "poste1", nom: "Poste niveau 1",  price: 1500, income: -50, ecologie: -1, economie: -2, bienEtre: 5, pop: 0, description: "La poste est un bâtiment peu couteux en entretien et peu polluant qui augmente le bien-être des habitants(quand les guichets sont ouverts)",x:0, y: -10, popMin: 100},
	{id: 6,name	: "centrale_hydraulique1", nom: "Centrale Hydraulique niveau 1",  price: 9500, income : -350, ecologie : 10, economie : -15, bienEtre: 0, pop: 0, description: "La centrale hydraulique est un bâtiment tres couteux en entretien mais qui permet produire de l'electricité de manière renouvelable, elle améliore donc beaucoup la statistique d'écologie.",x: -70, y:-40,sizeX: 1,sizeY: 2, popMin: 500},
	{id: 7,name : "panneau_solaire", nom: "Panneau solaire niveau 1",  price: 6500, income: -150, ecologie: 10, economie: -4, bienEtre: 0, pop: 0, description: "Les paneaux solaires sont assez couteux en entretien mais permettent de produire de l'electricité de maniere renouvelable.",x: 0, y:-100,sizeX: 2,sizeY:2, popMin: 400},
	{id: 8, name: "parc1", nom: "Parc niveau 1",  price: 1000, income: -75, ecologie: 10, economie: -5, bienEtre: 10, pop: 0, description: "Un parc apporte du bien être et du divertissement à la population, et permet à la ville de respiret augmentant donc la statistique d'écologie", x: 0,y:-10, popMin: 100},
	{id: 9, name: "usine_recyclage1", nom: "Usine de recyclage niveau 1",  price: 7500, income: -250, ecologie: 15, economie: -15, bienEtre: -10, pop: 0, description: "Une usine de recyclage est un bâtiment tres couteux en entretien mais qui permet de recycler les dechets de la ville.", x: 0,y:-10, popMin: 300},
	{id: 10, name: "banque1", nom: "Banque niveau 1",  price: 8500, income: 750, ecologie: -10, economie: 20, bienEtre: 5, pop: 0, description: "La banque est un batiment couteux en entretien, mais essentiel quelque soit la ville car elle permet d'augmenter grandement son économie.",x:30, y: -180, popMin: 600},
	{id: 11, name: "magasin1", nom: "Magasin niveau 1",  price: 1500, income: 300, ecologie: -3, economie: 15, bienEtre: 5, pop: 0, description: "Les magasins permettent à ville de faire vivre son économie. C'est un peu la base du commerce de chaque ville.",x:0, y: -10, popMin: 100},
	{id: 12, name: "usine1", nom: "Usine niveau 1",  price: 5000, income: 700, ecologie: -30, economie: 14, bienEtre: -10, pop: 0, description: "L'usine est un bâtiment très polluant et bruyant, mais qui contribue énormément à l'économie de la ville et rapporte beaucoup.", x:20, y: -10, popMin: 100},
	{id: 13, name: "mairie1", nom: "Mairie niveau 1",  price: 5000, income: -50, ecologie: 0, economie: 0, bienEtre: 0, pop: 0, description: "La mairie est le bâtiment à partir duquel vous allez pouvoir acheter des avancées technologiques. L'améliorer permet aussi de pouvoir améliorer les autres bâtiments.", x:0,y:-40, popMin: 0},
	{id: 14, name: "maison1", nom: "Maison niveau 1",  price: 1000, income: 100, ecologie: -5, economie: 5, bienEtre: 2, pop: 100, description: "Les maisons sont essentielles pour avoir des hâbitants dans la ville. Cependant elles demandent un petit coût en entretien et consomment un peu.",x:0,y:-40, popMin: 0},
];

let buildingListMk2 = [
	{id: 0,name: "caserne2", nom: "Caserne niveau 2",  price: 3500, income: -30, ecologie: -3, economie: -2.5, bienEtre: 10, pop: 0, description: "La caserne au niveau 2 possède une meilleure isolation avec des couts d'entretien réduits. Avoir une meilleure caserne des pompiers augmente encore plus le bien-être des habitants.",x:100,y:-100, popMin: 600},
	{id: 1,name : "centrale2", nom: "Centrale électrique niveau 2",  price: 8000, income : -120, ecologie: -8, economie: -5, bienEtre: -5, pop: 0, description: "La centrale au niveau 2 possède de meilleures techniques pour produire de l'électricité, moins polluantes, ce qui augmente donc les revenus et baisse moins l'écologie.",x:-100,y:-65,sizeX:1,sizeY:2, popMin: 1000},
	{id: 2,name : "commissariat2", nom: "Commissariat niveau 2",  price: 3500, income: -30, ecologie: -3, economie: -2.5, bienEtre: 10, pop: 0, description: "Le commissariat niveau 2 possède une meilleure isolation avec des couts d'entretien réduits. Avoir un meilleure commissariat augmente encore plus le bien-être des habitants, se sentant plus en sécurité.",x:10,y:-110, popMin: 600},
	{id: 3,name : "école2", nom: "Ecole niveau 2",  price: 3500, income: -30, ecologie: -3, economie: -2.5, bienEtre: 10, pop: 0, description: "L'école'au niveau 2 possède une meilleure isolation avec des couts d'entretien réduits. Avoir une meilleure école augmente encore plus le bien-être des habitants.",x:-100,y:-120,sizeX:1,sizeY:2, popMin: 600},
	{id: 4,name	: "hopital2", nom: "Hôpital niveau 2",  price : 3500, income: -30, ecologie: -3, economie: -2.5, bienEtre: 10, pop: 0, description: "L'hôpital'au niveau 2 possède une meilleure isolation avec des couts d'entretien réduits. Avoir un meilleur hôpital augmente encore plus le bien-être des habitants.",x:45,y:-20, popMin: 600},
	{id: 5,name : "poste2", nom: "Poste niveau 2",  price: 3500, income: -30, ecologie: -3, economie: -2.5, bienEtre: 10, pop: 0, description: "La poste  au niveau 2 possède une meilleure isolation avec des couts d'entretien réduits. Avoir une meilleure poste augmente encore plus le bien-être des habitants.",x:0,y:-40,sizeX:2,sizeY:1, popMin: 1000},
	{id: 6,name	: "centrale_hydraulique2", nom: "Centrale hydraulique niveau 2",  price: 12000, income : -250, ecologie : 20, economie : -9, bienEtre: -7, pop: 0, description: "La centrale hydraulique au niveau 2 est moins chère en entretien et permet de produire encore plus d'électricité, toujours de manière renouvelable.",x:30,y:-85,sizeX:2,sizeY:2, popMin: 1200},
	{id: 7,name : "panneau_solaire2", nom: "Panneau solaire niveau 2",  price: 9000, income: -100, ecologie: 15, economie: -2, bienEtre: 0, pop: 0, description: "Les panneaux solaires niveaux 2 sont moins couteux en entretien et permettent de produire plus d'électricité de manière renouvelable.",x: 0, y:-100,sizeX:2,sizeY:2, popMin: 600},
	{id: 8, name: "parc2", price: 2500, nom: "Parc niveau 2",  income: -80, ecologie: 15, economie: -8, bienEtre: 15, description: "Les parcs au niveau 2 sont moins couteux en entretien et sont plus modernes, augmentant ainsi le bien être des habitants.",x: 20, y:-110,sizeX:2,sizeY:2, popMin: 600},
	{id: 9, name: "usine_recyclage2", nom: "Usine de recyclage niveau 2",  price: 10000, income: -225, ecologie: 20, economie: -10, bienEtre: -5, pop: 0, description: "L'usine de recylcage au niveau 2 est moins couteuse en entretien et permet de recycler plus de dechets par jour.",x:-60,y:-110,sizeX:1,sizeY:2, popMin: 1000},
	{id: 10, name: "banque2", nom: "Banque niveau 2",  price: 12500, income: 1250, ecologie: -7, economie: 25, bienEtre: 7, pop: 0, description: "La banque au niveau 2 possède une meilleure isolation avec des coûts d'entretien réduits. Avoir une meilleure banque augmente les revenus et l'économie.",x:30, y: -180, popMin: 1200},
	{id: 11, name: "magasin2", nom: "Magasin niveau 2",  price: 2500, income: 450, ecologie: -5, economie: 18, bienEtre: 8, pop: 0, description: "Les magasins au niveau 2 possèdent une meilleure isolation, augmente les revenus et l'économie.",x:0,y:-40,sizeX:1,sizeY:2, popMin: 600},
	{id: 12, name: "usine2", nom: "Usine niveau 2",  price: 7500, income: 1000, ecologie: -20, economie: 19, bienEtre: -7, pop: 0, description: "Les usines au niveau 2 polluent moins et produisent plus, augmentant ainsi l'économie et les revenus.",x:-110,y:-90,sizeX:1,sizeY:2, popMin: 600},
	{id: 13, name: "mairie2", nom: "Mairie niveau 2",  price: 15000, income: 0, ecologie: 0, economie: 0, bienEtre: 0, pop: 0, description: "La mairie au niveau 2 permet de débloquer les améliorations des autres batiments et de nouvelles technologies.",x:-100,y:-100,sizeX:1,sizeY:2, popMin: 700},
	{id: 14, name: "maison2", nom: "Maison niveau 2",  price: 2500, income: 200, ecologie: -3, economie: 8, bienEtre: 5, pop: 300, description: "Les maisons de  niveau 2 ont une meilleure isolation et un coût d'entretien plus faible. Elles permettent aussi d'acceuillir plus de personne.",x:-20,y:-110,sizeX:1,sizeY:2, popMin: 0}
];

let buildingListMk3 = [
	{id: 0,name: "caserne3", nom: "Caserne niveau 3",  price: 5000, income: -10, ecologie: 5, economie: -1, bienEtre: 20, pop: 0, description: "La caserne au niveau 3 possède une bien meilleure isolation avec des couts d'entretien très réduits. Avoir une meilleure caserne des pompiers augmente encore plus le bien-être des habitants.",x:0,y:-50,sizeX:2,sizeY:1, popMin: 1200},
	{id: 1,name : "centrale3", nom: "Centrale électrique niveau 3",  price: 11000, income: -80, ecologie: -2, economie: -2, bienEtre: -1, pop: 0, description: "La centrale au niveau 3 possède de bien meilleures techniques pour produire de l'électricité, bien moins polluantes, ce qui augmente donc beaucoup les revenus et baisse bien moins l'écologie.",x:10,y:-110,sizeX:2,sizeY:2, popMin: 1500},
	{id: 2,name : "commissariat3", nom: "Commissariat niveau 3",  price: 5000, income: -15, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "Le commissariat niveau 3 possède une bien meilleure isolation avec des couts d'entretien très réduits. Avoir un meilleure commissariat augmente encore plus le bien-être des habitants, se sentant plus en sécurité.",x:20,y:-200,sizeX:2,sizeY:1, popMin: 1200},
	{id: 3,name : "école3", nom: "Ecole niveau 3",  price: 5000, income: -15, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "L'école'au niveau 3 possède une bien meilleure isolation avec des couts d'entretien très réduits. Avoir une meilleure école augmente encore plus le bien-être des habitants.",x:-20,y:-200,sizeX:1,sizeY:2, popMin: 1200},
	{id: 4,name	: "hopital3", nom: "Hôpital niveau 3",  price : 5000, income: -15, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "L'hôpital'au niveau 3 possède une bien meilleure isolation avec des couts d'entretien très réduits. Avoir un meilleur hôpital augmente encore plus le bien-être des habitants.",x:0,y:0,sizeX:2,sizeY:2, popMin: 1300},
	{id: 5,name : "poste3", nom: "Poste niveau 3",  price: 5000, income: -15, ecologie: -1, economie: -1, bienEtre: 20, pop: 0, description: "La poste  au niveau 3 possède une bien meilleure isolation avec des couts d'entretien très réduits. Avoir une meilleure poste augmente encore plus le bien-être des habitants.",x:10,y:-110,sizeX:2,sizeY:2, popMin: 1200},
	{id: 6,name	: "centrale_hydraulique3", nom: "Centrale hydraulique niveau 3",  price: 170000, income : -125, ecologie : 40, economie : -4, bienEtre: -3, pop: 0, description: "La centrale hydraulique au niveau 3 est bien moins chère en entretien et permet de produire encore plus d'électricité, toujours de manière renouvelable.",x:30,y:-140,sizeX:2,sizeY:2, popMin: 1500},
	{id: 7,name : "panneau_solaire3", nom: "Panneau solaire niveau 3",  price: 12000, income: -50, ecologie: 30, economie: -1, bienEtre: 0, pop: 0, description: "Les panneaux solaires niveaux 3 sont bien moins couteux en entretien et permettent de produire bien  plus d'électricité de manière renouvelable.",x: 10, y:-110,sizeX:2,sizeY:2, popMin: 1200},
	{id: 8, name: "parc3", nom: "Parc niveau 3",  price: 4000, income: -40, ecologie: 30, economie: -4, bienEtre: 30, pop: 0, description: "Les parcs au niveau 3 sont moins bien couteux en entretien et sont plus modernes, augmentant ainsi le bien être des habitants.",x: 0, y:-150,sizeX:2,sizeY:2, popMin: 1000},
	{id: 9, name: "usine_recyclage3", nom: "Usine de recyclage niveau 3",  price: 14000, income: -115, ecologie: 40, economie: -5, bienEtre: -3, pop: 0, description: "L'usine de recylcage au niveau 3 est bien moins couteuse en entretien et permet de recycler bien plus de dechets par jour.",x:10,y:-110,sizeX:2,sizeY:2, popMin: 2000},
	{id: 10, name: "banque3", nom: "Banque niveau 3",  price: 18000, income: 1700, ecologie: -4, economie: 40, bienEtre: 14, pop: 0, description: "La banque au niveau 3 possède une bien meilleure isolation avec des coûts d'entretien très réduits. Avoir une meilleure banque augmente beaucoup les revenus et l'économie.",x:-200,y:-200,sizeX:2,sizeY:2, popMin: 1200},
	{id: 11, name: "magasin3", nom: "Magasin niveau 3",  price: 4000, income: 700, ecologie: -3, economie: 30, bienEtre: 16, pop: 0, description: "Les magasins au niveau 3 possèdent une bien meilleure isolation, augmente beaucoup les revenus et l'économie.",x:10,y:-110,sizeX:2,sizeY:2, popMin: 1200},
	{id: 12, name: "usine3", nom: "Usine niveau 3",  price: 10000, income: 2000, ecologie: -10, economie: 35, bienEtre: -4, pop: 0, description: "Les usines au niveau 2 polluent beaucoup moins et produisent bien plus, augmentant ainsi l'économie et les revenus.",x:10,y:-180,sizeX:2,sizeY:2, popMin: 1500},
	{id: 13, name: "mairie3", nom: "Mairie niveau 3",  price: 15000, income: 0, ecologie: 0, economie: 0, bienEtre: 0, pop: 0, description: "La mairie au niveau 3 permet de débloquer les améliorations des autres batiments et de nouvelles technologies.",x:-200,y:-200,sizeX:2,sizeY:2, popMin: 1500},
	{id: 14, name: "maison3", nom: "Maison niveau 3",  price: 4000, income: 200, ecologie: -2, economie: 10, bienEtre: 10, pop: 500, description: "Les maisons de  niveau 3 ont une bien meilleure isolation et un coût d'entretien bien plus faible. Elles permettent aussi d'acceuillir beaucoup plus de personne.",x:-40,y:-200,sizeX:2,sizeY:2, popMin: 0}
];

let technologieT1 = [
	{id: 0, name: "feuMalvoyant", nom: "Feu Tricolore Malvoyant", price: 1000, ecologie: 0, economie: 0, bienEtre: 0, description: "Feu Tricolore Malvoyant."},
	{id: 1, name: "signalSonore", nom: "Signal Sonore", price: 1000, ecologie: 0, economie: 0, bienEtre: 0, description: "Signal Sonore pour Malvoyant."},
	{id: 2, name: "feuSmart", nom: "Feu Intelligent", price: 1000, ecologie: 0, economie: 0, bienEtre: 0, description: "Passe le feu au vert quand un véhicule de secours passe."},
	{id: 3, name: "peageVehiVert", nom: "Péage gratuit pour véhicule vert", price: 1000, ecologie: 0, economie: 0, bienEtre: 0, description: "Péage gratuit pour véhicule vert."},
	{id: 4, name: "e_Admin", nom: "e-administration", price: 1000, ecologie: 0, economie: 0, bienEtre: 0, description: "Application permettant de faire toutes les démarches administratives en ligne."},
	{id: 5, name: "dechetIntell", nom: "Système de gestion des déchets intelligents", price: 1000, ecologie: 0, economie: 0, bienEtre: 0, description: "Permet de trier les déchets de manière plus efficace."},
	{id: 6, name: "passageCamions", nom: "Passage des camions", price: 1000, ecologie: 0, economie: 0, bienEtre: 0, description: "Optimisation du passage des camions."},
	{id: 7, name: "capteurPoub", nom: "Capteur poubelle", price: 1000, ecologie: 0, economie: 0, bienEtre: 0, description: "Capteur pour voir si la poubelle est remplie ou non."},
	{id: 8, name: "LED", nom: "Lampadaire LED", price: 1000, ecologie: 0, economie: 0, bienEtre: 0, description: "Lampadaire LED."}
];

let technologieT2 = [
	{id: 0, name: "voitureElec", nom: "Voiture électrique", price: 2000, ecologie: 0, economie: 0, bienEtre: 0, description: "Voiture électrique."},
	{id: 1, name: "routeElec", nom: "Route qui recharge la batterie", price: 2000, ecologie: 0, economie: 0, bienEtre: 0, description: "Route qui recharge la batterie des voitures électriques"},
	{id: 2, name: "parkingSmart", nom: "Parking intelligent", price: 2000, ecologie: 0, economie: 0, bienEtre: 0, description: "Capteur sur parking, applications qui donne les places libres."},
	{id: 3, name: "bornes", nom: "Bornes connectées ", price: 2000, ecologie: 0, economie: 0, bienEtre: 0, description: "Bornes connectées guide les touristes, carte interactive."},
	{id: 4, name: "compacPoub", nom: "Compacteur poubelle", price: 2000, ecologie: 0, economie: 0, bienEtre: 0, description: "Compacteur sur la poubelle pour augmentater la capacité de stockage."},
	{id: 5, name: "IA_Trie", nom: "IA trie", price: 2000, ecologie: 0, economie: 0, bienEtre: 0, description: "IA permettant de facilité et d'améliorer davantage le tri des déchets."},
	{id: 6, name: "capteurMouv", nom: "Capteur de mouvement lampadaire", price: 2000, ecologie: 0, economie: 0, bienEtre: 0, description: "Permet de détecter la présence d'une personne la nuit pour allumer ou non un lampadaire."}
];

let technologieT3 = [
	{id: 0, name: "voitureAuto", nom: "Voiture autonome", price: 3000, ecologie: 0, economie: 0, bienEtre: 0, description: "Voiture capable d'aller à un point A à B sans conducteur"},
	{id: 1, name: "IAPolice", nom: "Robot policier", price: 3000, ecologie: 0, economie: 0, bienEtre: 0, description: "IA capable d'intéragir avec des personnes, peut localiser le danger et contacter les secours et intervenir en cas de danger."},
	{id: 2, name: "tuyauDech", nom: "Réseau de tuyaux souterrains pour déchets", price: 3000, ecologie: 0, economie: 0, bienEtre: 0, description: "Optimisation de la gestion des déchets."},
	{id: 3, name: "IAClean", nom: "Robot nettoyeur", price: 3000, ecologie: 0, economie: 0, bienEtre: 0, description: "Robot pour nettoyer les rues."},
	{id: 4, name: "capteurRes", nom: "Capteur sur les réseaux électriques, hydroliques", price: 3000, ecologie: 0, economie: 0, bienEtre: 0, description: "Capteur permettant de détecter les problèmes de fuites, dommages..."},
	{id: 5, name: "intelOpe", nom: "Intelligent operation center ", price: 3000, ecologie: 0, economie: 0, bienEtre: 0, description: "Visualisation de toutes les données, big data en temps réel de la ville"}	
];